# use a 256-color terminal definition and advertise true color support
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

unbind C-b
bind-key -r C-a send-prefix
set -g prefix C-a
set -g repeat-time 0
set -g focus-events on

set -g history-limit 10000
set -g mouse on
set -g extended-keys on
set -g extended-keys-format csi-u
set -g renumber-windows on
setw -g mode-keys vi

set -g status-left-length 20
set -g status-justify centre
set -g window-status-current-format " #I:#W#F "
set -g window-status-separator ""

if-shell "uname -s | grep -q Darwin" "source ~/.config/tmux/macos.conf"
